name: Sync settings

on:
  push:
    branches:
      - '*'

jobs:
  upload_settings:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Create TAR and Meta Files
        id: create_tar
        run: |
          for branch_folder in LiquidBounce/settings/*; do
            if [ -d "$branch_folder" ]; then
              echo "Processing files in directory: $branch_folder"
              branch_name=$(basename "$branch_folder")
              tar -cvf "$branch_name.tar" "$branch_folder" --transform='flags=r;s|/*||'
              for file in "$branch_folder"/*; do
                if [ -f "$file" ]; then
                  setting_id=$(basename "$file" | cut -f 1 -d '.')
                  contributors=$(git log --follow --format="%aN" -- "$file" | sort | uniq | paste -sd "," -)
                  echo "{\"setting_id\":\"$setting_id\",\"contributors\":\"$contributors\",\"timestamp\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > "$setting_id.meta"
                fi
              done
              tar -rvf "$branch_name.tar" "$branch_folder"/*.meta
            fi
          done

      - name: Upload TAR and Meta Files
        id: upload_files
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
        run: |
          for branch_folder in LiquidBounce/settings/*; do
            if [ -d "$branch_folder" ]; then
              branch_name=$(basename "$branch_folder")
              echo "Uploading tar file: $branch_name.tar"
              curl -X POST -H "Authorization: $AUTHORIZATION" -F "settings_bundle=@$branch_name.tar" "https://api.liquidbounce.net/api/v1/client/$branch_name/settings/upload/bundle"
            fi
          done
        
      - name: Upload TAR Files to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tar-artifacts
          path: ./*.tar